"""Unofficial PlexTrac API functions and types."""

from plextrac_api.functions.auth import (
    create_session,
    load_session,
    save_session,
    session_from_token,
)
from plextrac_api.functions.common import (
    PlexTracAuthError,
    PlexTracError,
    PlexTracGraphQLError,
    PlexTracNotFoundError,
    PlexTracPermissionError,
    PlexTracRateLimitError,
    execute_graphql,
    graphql_request,
    rest_request,
)
from plextrac_api.types import (
    AffectedAsset,
    Asset,
    AuthSession,
    Client,
    CodeSample,
    CustomField,
    Evidence,
    Finding,
    Identifier,
    JsonDict,
    Narrative,
    ObjectReference,
    Port,
    Report,
    UserRole,
    VulnerableParameter,
)

__all__ = [
    "AffectedAsset",
    "Asset",
    "AuthSession",
    "Client",
    "CodeSample",
    "CustomField",
    "Evidence",
    "Finding",
    "Identifier",
    "JsonDict",
    "Narrative",
    "ObjectReference",
    "PlexTracAuthError",
    "PlexTracError",
    "PlexTracGraphQLError",
    "PlexTracNotFoundError",
    "PlexTracPermissionError",
    "PlexTracRateLimitError",
    "Port",
    "Report",
    "UserRole",
    "VulnerableParameter",
    "create_session",
    "execute_graphql",
    "graphql_request",
    "load_session",
    "rest_request",
    "save_session",
    "session_from_token",
]
